### PR TITLE
Componentized video cards

### PR DESCRIPTION
**Pull request by Menkveld-24**
- Radio stations widget doesn't resize when there are no results found
- Moved video card to a shared component with many possible props
- Show which videos are already in the queue on searching

### CODE REVIEW

**Comment by ysbrandB** [comment]
image
The text on the on screen queue overflows when the title is too long

**Comment by ysbrandB** [comment]
image
also the title is behind the currentvideo progress bar again 😅

**Comment by ysbrandB** [comment]
I also think it is nice to have the roundness as a prop so the video-card has rounded corners in the queue to match all the other cards on the (admin) screen

**Comment by ysbrandB** [comment]
image
The white background div is not rounded and therefore is weird.
Also, the roundness of the div should be a prop so we can have square cards in the remote and round cards in the queue

**Review by Jessseee — APPROVED** [review]
LGTM

**Pull request merged**
